#ifndef DATABASECONNETC_GLOBAL_H
#define DATABASECONNETC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATABASECONNECT_LIBRARY)
#  define DATABASECONNECT_EXPORT Q_DECL_EXPORT
#else
#  define DATABASECONNECT_EXPORT Q_DECL_IMPORT
#endif

#endif // DATABASECONNETC_GLOBAL_H
